#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK_DIR="${WORK_DIR:-$ROOT_DIR/.single-node}"
CONF_DIR="$WORK_DIR/conf"
DATA_DIR="$WORK_DIR/data"
LOG_DIR="$WORK_DIR/log"
BIN_DIR="$WORK_DIR/bin"
BIN_PATH="$BIN_DIR/gobeansdb"
PID_FILE="$WORK_DIR/gobeansdb.pid"
STDOUT_LOG="$LOG_DIR/stdout.log"

LISTEN="${LISTEN:-0.0.0.0}"
HOSTNAME="${HOSTNAME:-127.0.0.1}"
MC_PORT="${MC_PORT:-7980}"
WEB_PORT="${WEB_PORT:-7988}"
DATA_HTTP_PORT="${DATA_HTTP_PORT:-7990}"
DATA_HTTP_TOKEN="${DATA_HTTP_TOKEN:-}"
THREADS="${THREADS:-4}"
NUM_BUCKET="${NUM_BUCKET:-16}"

usage() {
  cat <<EOF
Usage: $(basename "$0") [start|stop|restart|status|logs|genconf]

Environment overrides:
  WORK_DIR         (default: $ROOT_DIR/.single-node)
  LISTEN           (default: 0.0.0.0)
  HOSTNAME         (default: 127.0.0.1)
  MC_PORT          (default: 7980)
  WEB_PORT         (default: 7988)
  DATA_HTTP_PORT   (default: 7990)
  DATA_HTTP_TOKEN  (default: empty)
  THREADS          (default: 4)
  NUM_BUCKET       (default: 16)

Examples:
  $(basename "$0") start
  DATA_HTTP_TOKEN=change-me $(basename "$0") restart
EOF
}

ensure_dirs() {
  mkdir -p "$CONF_DIR" "$DATA_DIR" "$LOG_DIR" "$BIN_DIR"
}

bucket_list_16() {
  cat <<EOF
["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", a, b, c, d, e, f]
EOF
}

gen_conf() {
  ensure_dirs

  cat >"$CONF_DIR/global.yaml" <<EOF
# generated by scripts/run_single_node.sh
server:
  zkserves: []
  zkpath: "/beansdb/test"
  listen: $LISTEN
  port: $MC_PORT
  webport: $WEB_PORT
  data_http_listen: $LISTEN
  data_http_port: $DATA_HTTP_PORT
  data_http_auth_token: "$DATA_HTTP_TOKEN"
  data_http_access_log: $LOG_DIR/data_http_access.log
  threads: $THREADS
  errorlog: $LOG_DIR/gobeansdb.log
  accesslog: $LOG_DIR/access.log
  analysislog: $LOG_DIR/gobeansdb_analysis.log
  hostname: $HOSTNAME
  staticdir: $DATA_DIR
mc:
  max_key_len: 250
  max_req: 16
  body_max_str: 50M
  body_big_str: 5M
  body_c_str: 4K
  flush_max_str: 100M
hstore:
  data:
    flush_interval: 60
    flush_wake_str: 10M
    datafile_max_str: 1000M
    check_vhash: true
    no_gc_days: 7
  hint:
    hint_no_merged: false
    hint_split_cap_str: 1M
    hint_index_interval_str: 32K
    hint_merge_interval: 5
  htree:
    tree_height: 3
    tree_dump : 1
  local:
    homes:
    - $DATA_DIR
EOF

  cat >"$CONF_DIR/local.yaml" <<EOF
# generated by scripts/run_single_node.sh
server:
  port: $MC_PORT
  webport: $WEB_PORT
  data_http_listen: $LISTEN
  data_http_port: $DATA_HTTP_PORT
  data_http_auth_token: "$DATA_HTTP_TOKEN"
  data_http_access_log: $LOG_DIR/data_http_access.log
  errorlog: $LOG_DIR/gobeansdb.log
  accesslog: $LOG_DIR/access.log
  analysislog: $LOG_DIR/gobeansdb_analysis.log
hstore:
  data:
    flush_interval: 0
    flush_wake_str: 0
    no_gc_days: 0
  local:
    homes:
    - $DATA_DIR
  htree:
    tree_height: 3
    tree_dump : 1
  hint:
    hint_no_merged: false
EOF

  if [[ "$NUM_BUCKET" != "16" ]]; then
    echo "NUM_BUCKET=$NUM_BUCKET is not yet supported by this script. Use 16." >&2
    exit 1
  fi

  cat >"$CONF_DIR/route.yaml" <<EOF
# generated by scripts/run_single_node.sh
numbucket: $NUM_BUCKET
backup:
- "$HOSTNAME:$((MC_PORT + 1))"
main:
- addr: $HOSTNAME:$MC_PORT
  buckets: $(bucket_list_16)
EOF

  echo "Generated conf dir: $CONF_DIR"
}

build_bin() {
  ensure_dirs
  echo "Building gobeansdb binary..."
  (cd "$ROOT_DIR" && go build -o "$BIN_PATH" .)
}

is_running() {
  if [[ ! -f "$PID_FILE" ]]; then
    return 1
  fi
  local pid
  pid="$(cat "$PID_FILE")"
  if [[ -z "$pid" ]]; then
    return 1
  fi
  kill -0 "$pid" >/dev/null 2>&1
}

start() {
  if is_running; then
    echo "gobeansdb is already running (pid=$(cat "$PID_FILE"))"
    return 0
  fi

  gen_conf
  build_bin

  echo "Starting gobeansdb..."
  nohup "$BIN_PATH" -confdir "$CONF_DIR" >>"$STDOUT_LOG" 2>&1 &
  local pid=$!
  echo "$pid" >"$PID_FILE"

  sleep 1
  if kill -0 "$pid" >/dev/null 2>&1; then
    echo "Started gobeansdb (pid=$pid)"
    echo "MC      : $LISTEN:$MC_PORT"
    echo "Web     : $LISTEN:$WEB_PORT"
    echo "DataHTTP: $LISTEN:$DATA_HTTP_PORT"
    echo "Logs    : $LOG_DIR"
  else
    echo "Failed to start gobeansdb. Check logs: $STDOUT_LOG" >&2
    rm -f "$PID_FILE"
    exit 1
  fi
}

stop() {
  if ! is_running; then
    echo "gobeansdb is not running"
    rm -f "$PID_FILE"
    return 0
  fi

  local pid
  pid="$(cat "$PID_FILE")"
  echo "Stopping gobeansdb (pid=$pid)..."
  kill "$pid" >/dev/null 2>&1 || true

  for _ in {1..20}; do
    if ! kill -0 "$pid" >/dev/null 2>&1; then
      echo "Stopped"
      rm -f "$PID_FILE"
      return 0
    fi
    sleep 0.5
  done

  echo "Process did not exit in time, sending SIGKILL..."
  kill -9 "$pid" >/dev/null 2>&1 || true
  rm -f "$PID_FILE"
}

status() {
  if is_running; then
    echo "gobeansdb is running (pid=$(cat "$PID_FILE"))"
    echo "Conf dir: $CONF_DIR"
    echo "Data dir: $DATA_DIR"
    echo "Log dir : $LOG_DIR"
  else
    echo "gobeansdb is not running"
    exit 1
  fi
}

logs() {
  ensure_dirs
  touch "$STDOUT_LOG"
  tail -f "$STDOUT_LOG"
}

restart() {
  stop
  start
}

main() {
  local cmd="${1:-start}"
  case "$cmd" in
    start) start ;;
    stop) stop ;;
    restart) restart ;;
    status) status ;;
    logs) logs ;;
    genconf) gen_conf ;;
    -h|--help|help) usage ;;
    *)
      echo "unknown command: $cmd" >&2
      usage
      exit 2
      ;;
  esac
}

main "$@"
